Implementar caso de uso Manter Feira
marcosdosea/Feiragro pull request #126
Opened 2023-09-09 03:54 UTC by edutvares

2023-09-09 19:52 UTC, Fashion-Q requested changes
Reajustes no FeiraModel.

A "DataFim" não é um campo obrigatório no FeiraModel.

Não sei se é erro, mas no FeiraModel você colocou os "Navigation" e nos exemplo do professor não tem. Então isto não sei se deixa ou tira.

O Campo "Status" sempre que se cria uma feira, o campo está aberto. Então basta fazer
public string Status {get;set;} = "ABERTO"
sem os required.

De resto acho que está tudo certo.

2023-09-10 13:12 UTC, edutvares commented
O Navigation veio do scaffolding do banco. Está no projeto Core. Estou fazendo as demais alterações

2023-09-10 18:48 UTC, Fashion-Q commented
> O Navigation veio do scaffolding do banco. Está no projeto Core. Estou fazendo as demais alterações

Eu verifiquei no código e parece que isso está impedindo a validação do model. Remova essas partes de nagivation e deixe só os campos de validação.
 Também eu percebi que foi um equivoco meu falar sobre o campo status = "aberto". No banco de dados é "aberta" e acho que isso nem deveria exisitr nessa parte porque no banco ta como "aberta" no default. Acho que isso foi só um problema de g erencia de projeto.

2023-09-10 23:35 UTC, Fashion-Q approved these changes

2023-09-11 02:10 UTC, merged